# Jekyll sitesi oluşturma ve GitHub Pages'e dağıtma için örnek iş akışı
name: Jekyll ve GitHub Pages ile Dağıtım

on:
  # Ana dalına yapılan push'larda çalışır
  push:
    branches: ["main"]

  # Actions sekmesinden manuel olarak bu iş akışını çalıştırmanıza izin verir
  workflow_dispatch:

# GitHub Pages'e dağıtım için GITHUB_TOKEN izinlerini ayarlar
permissions:
  contents: read
  pages: write
  id-token: write

# Yalnızca bir eş zamanlı dağıtıma izin ver, kuyrukta bekleyen çalışmaları iptal etme.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Oluşturma işi
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sayfaları Yapılandır
        uses: actions/configure-pages@v5

      - name: Mevcut _site dizinini kaldır
        run: |
          if [ -d "_site" ]; then
            rm -rf _site
          fi

      - name: Jekyll ile Oluştur
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Artifact yükle
        uses: actions/upload-pages-artifact@v3

  # Dağıtım işi
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: GitHub Pages'e Dağıt
        id: deployment  
        uses: actions/deploy-pages@v4
